### ISSUE TITLE
Script not working. please fix

### ISSUE THREAD

**Issue by rakitanc** [Roki100/YouTube-rows-fix#1]
I am using Chrome browser Version 103.0.5060.114 (Official Build) (64-bit) On Pos OS linux

https://www.youtube.com/@GyanTherapy/videos

**Comment by Roki100** [comment]
Works fine for me set up to 6 rows, just to clarify - are you using the latest style version? (1.0.7)

![image](https://github.com/Roki100/YouTube-rows-fix/assets/35699619/5e0943bf-ad7d-40d4-8a8e-30864b794c75)

**Comment by rakitanc** [comment]
> Works fine for me set up to 6 rows, just to clarify - are you using the latest style version? (1.0.7)
> 
> ![image](https://user-images.githubusercontent.com/35699619/257959842-5e0943bf-ad7d-40d4-8a8e-30864b794c75.png)

Thanks for the reply mate, It means a lot

So the thing is, what i want basically is to fill the both black sides on my monitor to be utilized with the videos but it's not happening. So if you can help me achieve that it would be awesome

So this is how it looks currently and userstyles i am using

![Screenshot from 2023-08-03 04-59-22](https://github.com/Roki100/YouTube-rows-fix/assets/64612555/8339e673-359b-4f9a-a7c0-30a6fe43d3af)
![Screenshot from 2023-08-03 04-59-08](https://github.com/Roki100/YouTube-rows-fix/assets/64612555/b71bf9c3-9f6a-4d9d-ac8a-48a8dea204b3)

**Comment by Roki100** [comment]
Hey, now i understand your problem, could you please try pressing the cog and enabling resize thumbnails feature and try touching the slider if it can achieve that?

**Comment by rakitanc** [comment]
![Screenshot from 2023-08-03 19-38-03](https://github.com/Roki100/YouTube-rows-fix/assets/64612555/7ff3804b-af04-4662-8a19-9d4d14500fea)

Can you please explain what's this and can i have that too?

**Comment by sapondanaisriwan** [comment]
Try this.
```css
ytd-two-column-browse-results-renderer.grid:not(.grid-disabled):has(ytd-rich-grid-renderer:not([is-shorts-grid])) {
    max-width: 100% !important;
    width: 100% !important;
    #primary.ytd-two-column-browse-results-renderer {
        padding-inline: 20px;
    }
}
```
![image](https://github.com/Roki100/YouTube-rows-fix/assets/64634605/679993bb-8caf-4354-8084-79daea72b85a)
