### ISSUE TITLE
Thumbnails disappear when shorts aren't nuked

### ISSUE THREAD

**Issue by Roki100** [Roki100/YouTube-rows-fix#2]
There's an issue where theres blank space left in a size of ~1-2 thumbnails if shorts are not nuked by the userstyle, for now i have no idea on how to fix it without nuking shorts but I'm looking into it and any pull requests regarding this issue are appreciated

Nuking shorts from front/feed page via extensions like blocktube seem to take no effect either, but nuking it via userstyle seems to work, but it's not a solution to the issue

**Comment by sapondanaisriwan** [comment]
There are 2 ways what i figure out.
1. Group the shorts section at the top of the page.
```css
ytd-rich-section-renderer { order: -1; }
```
2. Overwrite a function that YouTube use to calculate the elements per row before it was invoked (impossible with userstyle)

**Comment by Roki100** [comment]
That's interesting, while the 1. solution is not perfect as i doubt anyone would want shorts to be on top, it is certainly better than removing them entirely

For the 2. solution - it seems to be a better idea even if it would involve making a separate userscript for this, i also thought about this one but it sounds a bit complex to find that exact function and integrate into it without issues

**Comment by Roki100** [comment]
I have added an experimental userscript that sorta fixes the problem in [79f1213](https://github.com/Roki100/YouTube-rows-fix/commit/79f12134e5042180aac05245311905fec14c8271), feel free to take a look!

**Comment by JourneyOver** [comment]
Try this css out @Roki100 and see if it works for you:

```css
[page-subtype="home"] ytd-rich-grid-row,
[page-subtype="home"] ytd-rich-grid-row #contents {
  display: contents;
}

ytd-rich-section-renderer,
.ghost-grid.ytd-ghost-grid-renderer {
  display: none;
}

[page-subtype="home"] #contents > ytd-rich-item-renderer:has(#content > ytd-ad-slot-renderer) {
  display: none;
}
```
